# Generated by Django 3.1.7 on 2021-04-06 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210406_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='clientlot',
            options={'verbose_name': 'Лот клієнтів', 'verbose_name_plural': 'Лоти клієнтів'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата і час завершення'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.client', verbose_name='Власник лоту'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стартова ціна'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='price_gap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Ціна, на яку можуть змінювати ціну ставки)', max_digits=6, verbose_name='Зміна ціни'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата і час завершення'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.company', verbose_name='Власник лоту'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стартова ціна'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='price_gap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(Ціна, на яку можуть змінювати ціну ставки)', max_digits=6, verbose_name='Зміна ціни'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
