# Generated by Django 3.1.7 on 2021-04-06 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210406_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='clientlot',
            options={'verbose_name': 'Лот клієнта', 'verbose_name_plural': 'Лоти клієнта'},
        ),
        migrations.AlterModelOptions(
            name='clientreview',
            options={'verbose_name': 'Відгук компанії', 'verbose_name_plural': 'Відгуки компаній'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компанія', 'verbose_name_plural': 'Компанії'},
        ),
        migrations.AlterModelOptions(
            name='companylot',
            options={'verbose_name': 'Лот компаній', 'verbose_name_plural': 'Лоти компаній'},
        ),
        migrations.AlterModelOptions(
            name='companyreview',
            options={'verbose_name': 'Відгук клієнта', 'verbose_name_plural': 'Відгуки клієнтів'},
        ),
        migrations.AlterField(
            model_name='clientreview',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
