# Generated by Django 3.1.7 on 2021-04-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210406_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LotPhotos',
            new_name='LotPhoto',
        ),
    ]
