# Generated by Django 3.1.7 on 2021-04-06 21:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210406_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylot',
            options={'verbose_name': 'Лот компанії', 'verbose_name_plural': 'Лоти компаній'},
        ),
        migrations.AlterModelOptions(
            name='lotphoto',
            options={'verbose_name': 'Фотографія лота', 'verbose_name_plural': 'Фотографії лотів'},
        ),
        migrations.AlterField(
            model_name='lotphoto',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.companylot'),
        ),
        migrations.AlterField(
            model_name='lotphoto',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, null=True, quality=100, size=[1000, 1000], upload_to='lot_photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='BidClientLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiden_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стартова ціна')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.clientlot')),
            ],
        ),
    ]
