# Generated by Django 3.1.7 on 2021-04-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210407_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCompanyLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiden_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стартова ціна')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.clientlot')),
            ],
        ),
    ]
