# Generated by Django 3.1.7 on 2021-05-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_bidcompanylot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidclientlot',
            options={'verbose_name': 'Ставка на лот клієнта', 'verbose_name_plural': 'Ставки на лот клієнта'},
        ),
        migrations.AlterModelOptions(
            name='bidcompanylot',
            options={'verbose_name': 'Ставка на лот компанії', 'verbose_name_plural': 'Ставки на лот компанії'},
        ),
        migrations.AddField(
            model_name='clientlot',
            name='current_price',
            field=models.PositiveIntegerField(default=None, verbose_name='Ціна зараз'),
        ),
        migrations.AddField(
            model_name='clientlot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companylot',
            name='current_price',
            field=models.PositiveIntegerField(default=None, verbose_name='Ціна зараз'),
        ),
        migrations.AddField(
            model_name='companylot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bidclientlot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='bidcompanylot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Стартова ціна'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Стартова ціна'),
        ),
        migrations.AlterField(
            model_name='lotphoto',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.companylot'),
        ),
    ]
