# Generated by Django 3.1.7 on 2021-05-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210506_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlot',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата і час завершення'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата і час завершення'),
        ),
    ]
