# Generated by Django 3.1.7 on 2021-05-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210511_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidcompanylot',
            name='bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.client', verbose_name='bid'),
        ),
    ]
