# Generated by Django 3.1.7 on 2021-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210517_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlot',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Ціна зараз'),
        ),
        migrations.AlterField(
            model_name='clientlot',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Ціна зараз'),
        ),
        migrations.AlterField(
            model_name='companylot',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Посилання'),
        ),
    ]
