# Generated by Django 3.1.7 on 2021-05-25 12:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='categories/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
